CREATE TABLE ACHADMIN.XB_COUNTRIES(
    COUNTRY_CODE VARCHAR2(2) NOT NULL,
	SG_BIC VARCHAR2(8) NOT NULL,
	OVERSEAS_BIC VARCHAR2(8) NOT NULL,
	OVERSEAS_GW_SHORTCODE VARCHAR2(4) NOT NULL,
    PRIMARY KEY ("COUNTRY_CODE")
);